import { SongData } from '../types/song';

export const SAMPLE_SONGS: SongData[] = [
  {
    id: 'sample-2',
    title: 'Midnight Echoes',
    artist: 'Luna Solaris',
    sourceType: 'sample',
    audioUrl: '',
    duration: 62,
    metadata: {
      title: 'Midnight Echoes',
      artist: 'Luna Solaris',
      genre: 'Acoustic Indie Rock',
      bpm: 96,
      key: 'G Major',
      duration: 62,
      mood: 'Nostalgic, Heartfelt, Melodic',
      energyLevel: 'Medium',
      vocalStyle: 'Warm Acoustic / Folk Lead',
    },
    lyrics: [
      { id: 'm1', time: 2.0, endTime: 6.0, section: 'Intro', text: 'Footsteps on the quiet wooden floor', syllables: 9, chords: 'G - Em', rhymeKey: 'A' },
      { id: 'm2', time: 6.5, endTime: 10.5, section: 'Verse 1', text: 'Watching shadows dancing by the door', syllables: 9, chords: 'C - D', rhymeKey: 'A' },
      { id: 'm3', time: 11.0, endTime: 15.0, section: 'Verse 1', text: 'All the memories that we used to share', syllables: 10, chords: 'G - Em', rhymeKey: 'B' },
      { id: 'm4', time: 15.5, endTime: 19.5, section: 'Verse 1', text: 'Lingering like perfume in the autumn air', syllables: 11, chords: 'C - D', rhymeKey: 'B' },
      { id: 'm5', time: 20.0, endTime: 24.5, section: 'Chorus', text: 'Sing into the midnight, hear the echo cry', syllables: 11, chords: 'Em - C', rhymeKey: 'C' },
      { id: 'm6', time: 25.0, endTime: 29.5, section: 'Chorus', text: 'Underneath the silver of a timeless sky', syllables: 11, chords: 'G - D', rhymeKey: 'C' },
      { id: 'm7', time: 30.0, endTime: 34.5, section: 'Chorus', text: 'Every word you told me still rings true', syllables: 9, chords: 'Em - C', rhymeKey: 'D' },
      { id: 'm8', time: 35.0, endTime: 40.0, section: 'Chorus', text: 'Midnight echoes calling back to you', syllables: 9, chords: 'D - G', rhymeKey: 'D' },
      { id: 'm9', time: 40.5, endTime: 45.0, section: 'Bridge', text: 'Time moves on, but the melodies remain', syllables: 11, chords: 'Am - Em', rhymeKey: 'E' },
      { id: 'm10', time: 45.5, endTime: 51.0, section: 'Bridge', text: 'Washing away all the sorrow and the pain', syllables: 12, chords: 'C - D', rhymeKey: 'E' },
      { id: 'm11', time: 51.5, endTime: 58.0, section: 'Outro', text: 'Back to you... in the midnight rain', syllables: 8, chords: 'G - D - G', rhymeKey: 'E' },
    ],
    agentTrace: [
      { id: 't1', timestamp: '00:00.10', step: 'Sandbox Initialization', tool: 'AntigravitySandbox', status: 'completed', details: 'Initialized Antigravity Agent sandbox container.' },
      { id: 't2', timestamp: '00:00.40', step: 'Spectrogram & Rhythm Tracking', tool: 'AudioSpectrogramAnalysis', status: 'completed', details: 'Detected 96 BPM, Key: G Major, warm acoustic timbre.' },
      { id: 't3', timestamp: '00:00.80', step: 'Phonetic Transcription', tool: 'PhonemeDetector', status: 'completed', details: 'Transcribed acoustic vocal lines with pitch contour tags.' },
      { id: 't4', timestamp: '00:01.20', step: 'Syllabic & Rhyme Analysis', tool: 'MetricMeterMapper', status: 'completed', details: 'Identified steady 9-11 syllable folk ballad meter.' },
    ],
    isAnalyzed: true,
  },
  {
    id: 'sample-3',
    title: 'Electric Horizon',
    artist: 'Circuit Breaker',
    sourceType: 'sample',
    audioUrl: '',
    duration: 58,
    metadata: {
      title: 'Electric Horizon',
      artist: 'Circuit Breaker',
      genre: 'EDM / Dance Anthem',
      bpm: 130,
      key: 'F Major',
      duration: 58,
      mood: 'Euphoric, Festival, Driving Bass',
      energyLevel: 'Very High',
      vocalStyle: 'Vibrant Electro Belt',
    },
    lyrics: [
      { id: 'e1', time: 2.5, endTime: 6.5, section: 'Intro', text: 'Feel the bass vibrating through the ground', syllables: 10, chords: 'F - Dm', rhymeKey: 'A' },
      { id: 'e2', time: 6.8, endTime: 11.0, section: 'Intro', text: 'Lost inside the symphony of sound', syllables: 9, chords: 'Bb - C', rhymeKey: 'A' },
      { id: 'e3', time: 11.5, endTime: 15.5, section: 'Verse 1', text: 'Lights are flashing bright in neon blue', syllables: 9, chords: 'F - Dm', rhymeKey: 'B' },
      { id: 'e4', time: 15.8, endTime: 20.0, section: 'Verse 1', text: 'Tonight is made for me and you', syllables: 8, chords: 'Bb - C', rhymeKey: 'B' },
      { id: 'e5', time: 20.5, endTime: 24.5, section: 'Pre-Chorus', text: 'Hands up high, feel the rhythm take control', syllables: 11, chords: 'Dm - Bb', rhymeKey: 'C' },
      { id: 'e6', time: 25.0, endTime: 29.5, section: 'Chorus', text: 'We are the fire on the electric horizon', syllables: 13, chords: 'F - C', rhymeKey: 'D' },
      { id: 'e7', time: 30.0, endTime: 34.5, section: 'Chorus', text: 'A thousand sparks, our spirits keep on risin’', syllables: 11, chords: 'Dm - Bb', rhymeKey: 'D' },
      { id: 'e8', time: 35.0, endTime: 39.5, section: 'Chorus', text: 'Nothing can stop the energy tonight', syllables: 11, chords: 'F - C', rhymeKey: 'E' },
      { id: 'e9', time: 40.0, endTime: 45.0, section: 'Chorus', text: 'Dancing together in the golden light', syllables: 10, chords: 'Bb - F', rhymeKey: 'E' },
      { id: 'e10', time: 45.5, endTime: 52.0, section: 'Outro', text: 'Electric horizon... light up the night!', syllables: 10, chords: 'F - C - F', rhymeKey: 'E' },
    ],
    agentTrace: [
      { id: 't1', timestamp: '00:00.15', step: 'Sandbox Initialization', tool: 'AntigravitySandbox', status: 'completed', details: 'Spun up Antigravity sandbox session.' },
      { id: 't2', timestamp: '00:00.42', step: 'Transient Peak & Beat Grid', tool: 'AudioSpectrogramAnalysis', status: 'completed', details: 'Detected four-on-the-floor 130 BPM, Key: F Major.' },
      { id: 't3', timestamp: '00:00.85', step: 'Vocal Stem Alignment', tool: 'PhonemeDetector', status: 'completed', details: 'Mapped vocal drop and lyrical hook points.' },
    ],
    isAnalyzed: true,
  }
];
